default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || '5432' %>
  database: <%= ENV['DB_NAME'] || 'fetchpark' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  pool: 5

development:
  <<: *default
  database: fetch-api_development

test:
  <<: *default
  database: fetch-api_test

production:
  <<: *default
